/*

*/
#include <iostream>
#include <cstdio>
#include <iomanip>
#include <stdio.h>
#include <chrono>
#include <ctime> 
#include <fstream>
#include <string.h>
#include <string>
using namespace std;

//temp variables hard coded for testing, these will be populated by user input
string fname = "Dan", lname="Pobidel", address = "400 Road st, New britain, CT, 06051", account;
int dob[3]= {07,10,1999};
int pin = 0000;
long verificationCode=100000000000000000;
int transactions[512]={20,10,5,5,-10};
string tranDates[512]={"01/01/2021","01/02/2021","01/03/2021","01/04/2021","01/05/2021"};

//Dan
void loadOutputFileTemplate(const char *filename){
    string header = "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~Bank of Piggy~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n";
    string accountInfo = fname + " " + lname + "\n" + to_string(dob[0])+ "/" + to_string(dob[1])+ "/" + to_string(dob[2]) + "\n" + address + "\n" + "Account #: " + account + "\n\n";
    string transHeader = "Transactions \n~~~~~~~~~~~~~\n";
    string footer = "\n\n\n\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" + to_string(verificationCode) + "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~";
    string fileTemplate = header + accountInfo + transHeader + footer;

    FILE *f;
    f=fopen(filename, "w");
    fputs(fileTemplate.c_str(), f);
    fclose(f);
}

//Dan
//This function is used for the creation of a new account file
//Name of file generated by users last name + "PiggyCard" + timestamp of creation
//calls function to populate new file with template
void createOutputFile(){
    FILE *f;
    time_t t = time(0);   // get time now
    tm* currTime = std::localtime(&t);
    string timestamp = to_string((currTime->tm_mon + 1)) + "." + to_string(currTime->tm_mday) + "."+ to_string((currTime->tm_year + 1900))+"." 
                      + to_string(currTime->tm_hour-4) + "." + to_string(currTime->tm_min) + "." + to_string(currTime->tm_sec) ;

    string filename = lname + "_PiggyCard_" + timestamp + ".txt";
    account = timestamp;

    f=fopen(filename.c_str(), "w");
    fclose(f);

    loadOutputFileTemplate((filename).c_str());
}


int main(){
    createOutputFile();

    return 0;
}



