output: PiggyBank.o 
	g++ -lcrypto PiggyBank.o -o output

PiggyBank.o: PiggyBank.cpp
	g++ -c PiggyBank.cpp

Navigation.o: Navigation.cpp
	g++ -c Navigation.cpp

helpers.o: helpers.cpp
	g++ -c helpers.cpp

clean:
	rm *.o output